### ISSUE TITLE
Add pylint support

### ISSUE THREAD

**Issue by romainrichard** [adamchainz/multilint#16]
Those are the linters I see missing from the project, some of those get installed but it doesn't look like we can specify them in the config to ask multilint to run them (haven't actually tried so I may be wrong).

**Comment by adamchainz** [comment]
mccabe, pyflakes, and pep8 (now pycodestyle) are all run by `flake8`, just use that. You can also run `flake8-pep257` to run that under flake8.

I don't like how strict `pylint` is myself and so don't use it on my projects, but I'd accept a PR that runs it.
