### ISSUE TITLE
Run on a specific file only

### ISSUE THREAD

**Issue by arthurio** [adamchainz/multilint#82]
We'd like to run `multilint` only on the changed files to test regression only (while we cleanup the rest of the code base).  Would it be possible to add positional arguments to the command that would accept file paths (and override `settings['paths']`)?

```shell
multilint path/file1.py path/file2.py
```

If you are ok with the idea, I'd be happy to submit a PR.

**Comment by adamchainz** [comment]
Sounds good to me, I've thought of adding this myself but haven't really needed it.
